include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

image: node:lts-alpine

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

pages:
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
